name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Create build dir
        run: mkdir build
      - name: Compile Manual
        # TODO: run `make build/jediacademy_plugins_doc.pdf` instead,
        # but that requires pdflatex to be installed
        uses: dante-ev/latex-action@latest
        with:
          working_directory: build
          root_file: ../jediacademy_plugins_doc.tex
      - name: Package plugin
        run: make build/jediacademy.zip
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          prerelease: true
          body: |
            Automatic pre-release build.
            
            The jediacademy.zip file can be installed using the button in Blender's add-on preferences.
            
            Please consult jediacademy_plugins_doc.pdf for instructions on how to use the plugin.
            
            Latest change:
            
            ${{github.event.commits[0].message}}
          files: |
            build/jediacademy_plugins_doc.pdf
            build/jediacademy.zip
